name: interpython
channels:
- bioconda
- defaults
dependencies:
- biopython=1.70=np112py27_1
- jupyter=1.0.0=py27_3
- libpng=1.6.30=1
- libtiff=4.0.6=3
- matplotlib=2.0.2=np112py27_0
- networkx=1.11=py27_0
- notebook=5.0.0=py27_0
- numpy=1.12.1=py27_0
- pandas=0.20.3=py27_0
- pillow=4.2.1=py27_0
- pip=9.0.1=py27_1
- python=2.7.13=0
- scikit-image=0.13.0=np112py27_0
- scikit-learn=0.19.0=np112py27_0
- scipy=0.19.1=np112py27_0
- seaborn=0.8=py27_0
- setuptools=36.4.0=py27_0
- pip:
  - tifffile
