name: interpython3
channels:
- bioconda
- defaults
dependencies:
- biopython=1.70=np112py35_1
- matplotlib=2.0.2=np112py35_0
- networkx=1.11=py35_0
- numpy=1.12.1=py35_0
- pandas=0.20.3=py35_0
- pillow=4.2.1=py35_0
- python=3.5.4=0
- scikit-image=0.13.0=np112py35_0
- scikit-learn=0.19.0=np112py35_0
- scipy=0.19.1=np112py35_0
- seaborn=0.8=py35_0
